package threads;

public class ResultTask extends Thread{
    public void run(){
        System.out.println("Result generated by :"+ Thread.currentThread().getName());
    }
    public static void main(String[] args) {
        ResultTask t1=new ResultTask();
        t1.run();//doesn't create new thread it runs on main thread//Normal Execution
        t1.start();//creates a new thread//Multi Threading->T-0,T-1,T-2 & so on
        //start() internally calls run
        //Thread cannot be started twice
    }
}
